"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _movies_list from './movies-list.bones.json'
import _movie_poster from './movie-poster.bones.json'
import _movie_title from './movie-title.bones.json'
import _movie_tagline from './movie-tagline.bones.json'
import _movie_genres from './movie-genres.bones.json'
import _movie_overview from './movie-overview.bones.json'
import _movie_runtime from './movie-runtime.bones.json'
import _movie_watch_btn from './movie-watch-btn.bones.json'

configureBoneyard({"color":"#1a1a1a","darkColor":"#2a2a2a","animate":"shimmer","darkShimmerColor":"#333333","speed":"1.5s"})

registerBones({
  "movies-list": _movies_list,
  "movie-poster": _movie_poster,
  "movie-title": _movie_title,
  "movie-tagline": _movie_tagline,
  "movie-genres": _movie_genres,
  "movie-overview": _movie_overview,
  "movie-runtime": _movie_runtime,
  "movie-watch-btn": _movie_watch_btn,
})
