"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _movies_list from './movies-list.bones.json'
import _tv_list from './tv-list.bones.json'

registerBones({
  "movies-list": _movies_list,
  "tv-list": _tv_list,
})
